/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261Project;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author msb5626
 */
public class jpButtons extends javax.swing.JPanel {

    /**
     * Creates new form jpMain
     */
    public jpButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAddSection = new javax.swing.JButton();
        jbNewProfessor = new javax.swing.JButton();
        jbNewClass = new javax.swing.JButton();
        jbNewSchedule = new javax.swing.JButton();
        jbConstraints = new javax.swing.JButton();

        jbAddSection.setText("Add Section");
        jbAddSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddSectionActionPerformed(evt);
            }
        });

        jbNewProfessor.setText("New Professor");
        jbNewProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewProfessorActionPerformed(evt);
            }
        });

        jbNewClass.setText("New Class");
        jbNewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewClassActionPerformed(evt);
            }
        });

        jbNewSchedule.setText("New Schedule");
        jbNewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewScheduleActionPerformed(evt);
            }
        });

        jbConstraints.setText("Check Constraints");
        jbConstraints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConstraintsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAddSection)
                .addGap(18, 18, 18)
                .addComponent(jbNewProfessor)
                .addGap(18, 18, 18)
                .addComponent(jbNewClass)
                .addGap(18, 18, 18)
                .addComponent(jbNewSchedule)
                .addGap(18, 18, 18)
                .addComponent(jbConstraints)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddSection)
                    .addComponent(jbNewProfessor)
                    .addComponent(jbNewClass)
                    .addComponent(jbNewSchedule)
                    .addComponent(jbConstraints))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNewProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewProfessorActionPerformed
        // TODO add your handling code here:
        String strProfessorID;
        String strFName;
        String strLName;
        String strCourseLoad;
        String strUsername;
        String strDepartment;
        
        JTextField jtfID = new JTextField();
        JTextField jtfFName = new JTextField();
        JTextField jtfLName = new JTextField();
        JTextField jtfCourseLoad = new JTextField();
        JTextField jtfUsername = new JTextField();
        JTextField jtfDepartment = new JTextField();
        
        final JComponent[] inputs = new JComponent[] 
        {
           new JLabel("Professor ID"),
           jtfID,
           new JLabel("First Name"),
           jtfFName,
           new JLabel("Last Name"),
           jtfLName,
           new JLabel("Courseload (credits)"),
           jtfCourseLoad,
           new JLabel("Username"),
           jtfUsername,
           new JLabel("Department"),
           jtfDepartment
        };
        
int result = JOptionPane.showConfirmDialog(null, inputs, "New Professor Info", JOptionPane.PLAIN_MESSAGE);
if (result == JOptionPane.OK_OPTION) 
{
   strProfessorID = jtfID.getText();
   strFName = jtfFName.getText();
   strLName = jtfLName.getText();
   strCourseLoad = jtfCourseLoad.getText();
   strUsername = jtfUsername.getText();
   strDepartment = jtfDepartment.getText();
    System.out.println("You entered \n" 
            + "Professor ID  "  + strProfessorID + "\n"
            + "First Name  "  + strFName + "\n"
            + "Last Name  "  +  strLName + "\n"
            + "Courseload    "  + strCourseLoad + "\n"
            + "Username    "  + strUsername + "\n"
            + "Department   " + strDepartment + "\n"
    );
} else {
    System.out.println("User canceled / closed the dialog, result = " + result);
}
    }//GEN-LAST:event_jbNewProfessorActionPerformed

    private void jbAddSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddSectionActionPerformed
        // TODO add your handling code here:
        String strSectionID;
        String strProfessorCourseID;
        String strRoomTimeID;
        String strSectionNumber;
                
        JTextField jtfSectionID = new JTextField();
        /JTextField jtfProfessorCourse = new JTextField();
        /JTextField jtfRoomTimeID = new JTextField();
        JTextField jtfSectionNumber = new JTextField();
        
        final JComponent[] inputs = new JComponent[] 
        {
           new JLabel("Section ID"),
           jtfSectionID,
           new JLabel("Professor Course ID"),
           /jtfCredits,
           new JLabel("Estimated Students"),
           /jtfEstStudents,
           new JLabel("Name"),
           jtfName,
           new JLabel("Major"),
           jtfMajor,
           new JLabel("Level"),
           jtfLevel
        };
        
int result = JOptionPane.showConfirmDialog(null, inputs, "New Professor Info", JOptionPane.PLAIN_MESSAGE);
if (result == JOptionPane.OK_OPTION) 
{
   strCourseID = jtfCourseID.getText();
   strCredits = jtfCredits.getText();
   strEstStudents = jtfEstStudents.getText();
   strName = jtfName.getText();
   strMajor = jtfMajor.getText();
   strLevel = jtfLevel.getText();
    System.out.println("You entered \n" 
            + "Course ID  "  + strCourseID + "\n"
            + "Credits  "  + strCredits + "\n"
            + "Estimated Students  "  +  strEstStudents + "\n"
            + "Name    "  + strName + "\n"
            + "Major    "  + strMajor + "\n"
            + "Level   " + strLevel + "\n"
    );
} else {
    System.out.println("User canceled / closed the dialog, result = " + result);
}
    }//GEN-LAST:event_jbAddSectionActionPerformed

    private void jbNewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewClassActionPerformed
        // TODO add your handling code here:
        String strCourseID;
        String strCredits;
        String strEstStudents;
        String strName;
        String strMajor;
        String strLevel;
        
        JTextField jtfCourseID = new JTextField();
        JTextField jtfCredits = new JTextField();
        JTextField jtfEstStudents = new JTextField();
        JTextField jtfName = new JTextField();
        JTextField jtfMajor = new JTextField();
        JTextField jtfLevel = new JTextField();
        
        final JComponent[] inputs = new JComponent[] 
        {
           new JLabel("Course ID"),
           jtfCourseID,
           new JLabel("Credits"),
           jtfCredits,
           new JLabel("Estimated Students"),
           jtfEstStudents,
           new JLabel("Name"),
           jtfName,
           new JLabel("Major"),
           jtfMajor,
           new JLabel("Level"),
           jtfLevel
        };
        
int result = JOptionPane.showConfirmDialog(null, inputs, "New Professor Info", JOptionPane.PLAIN_MESSAGE);
if (result == JOptionPane.OK_OPTION) 
{
   strCourseID = jtfCourseID.getText();
   strCredits = jtfCredits.getText();
   strEstStudents = jtfEstStudents.getText();
   strName = jtfName.getText();
   strMajor = jtfMajor.getText();
   strLevel = jtfLevel.getText();
    System.out.println("You entered \n" 
            + "Course ID  "  + strCourseID + "\n"
            + "Credits  "  + strCredits + "\n"
            + "Estimated Students  "  +  strEstStudents + "\n"
            + "Name    "  + strName + "\n"
            + "Major    "  + strMajor + "\n"
            + "Level   " + strLevel + "\n"
    );
} else {
    System.out.println("User canceled / closed the dialog, result = " + result);
}
    }//GEN-LAST:event_jbNewClassActionPerformed

    private void jbNewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewScheduleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbNewScheduleActionPerformed

    private void jbConstraintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConstraintsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbConstraintsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddSection;
    private javax.swing.JButton jbConstraints;
    private javax.swing.JButton jbNewClass;
    private javax.swing.JButton jbNewProfessor;
    private javax.swing.JButton jbNewSchedule;
    // End of variables declaration//GEN-END:variables
}
