/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261Project;

/**
 *
 * @author msb5626
 */
public class jpButtons extends javax.swing.JPanel {

    /**
     * Creates new form jpMain
     */
    public jpButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAddSection = new javax.swing.JButton();
        jbNewProfessor = new javax.swing.JButton();
        jbNewClass = new javax.swing.JButton();
        jbNewSchedule = new javax.swing.JButton();
        jbConstraints = new javax.swing.JButton();

        jbAddSection.setText("Add Section");
        jbAddSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddSectionActionPerformed(evt);
            }
        });

        jbNewProfessor.setText("New Professor");
        jbNewProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewProfessorActionPerformed(evt);
            }
        });

        jbNewClass.setText("New Class");
        jbNewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewClassActionPerformed(evt);
            }
        });

        jbNewSchedule.setText("New Schedule");
        jbNewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewScheduleActionPerformed(evt);
            }
        });

        jbConstraints.setText("Check Constraints");
        jbConstraints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConstraintsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAddSection)
                .addGap(18, 18, 18)
                .addComponent(jbNewProfessor)
                .addGap(18, 18, 18)
                .addComponent(jbNewClass)
                .addGap(18, 18, 18)
                .addComponent(jbNewSchedule)
                .addGap(18, 18, 18)
                .addComponent(jbConstraints)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddSection)
                    .addComponent(jbNewProfessor)
                    .addComponent(jbNewClass)
                    .addComponent(jbNewSchedule)
                    .addComponent(jbConstraints))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNewProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNewProfessorActionPerformed

    private void jbAddSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddSectionActionPerformed

    private void jbNewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNewClassActionPerformed

    private void jbNewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNewScheduleActionPerformed

    private void jbConstraintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConstraintsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConstraintsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddSection;
    private javax.swing.JButton jbConstraints;
    private javax.swing.JButton jbNewClass;
    private javax.swing.JButton jbNewProfessor;
    private javax.swing.JButton jbNewSchedule;
    // End of variables declaration//GEN-END:variables
}
